version: '3.5'

networks:
  backend:
  frontend:
    external:
      name: dws_nginx

services:
  database:
    container_name: '${PROJECT_NAME}_mysql'
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ${PROJECT_ROOT}/_database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - backend

  wordpress:
    container_name: '${PROJECT_NAME}_wordpress'
    image: wordpress:latest
    restart: unless-stopped
    depends_on:
      - database
    expose:
      - '80'
    volumes:
      - ${PROJECT_ROOT}/wordpress:/var/www/html
      - ../bin/install-wp.sh:/usr/local/bin/install-wp.sh:ro
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini:ro
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
      VIRTUAL_HOST: '${PROJECT_HOST}'
      VIRTUAL_PORT: 80
    networks:
      - backend
      - frontend

  phpmyadmin:
    container_name: '${PROJECT_NAME}_phpmyadmin'
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    expose:
      - '80'
    environment:
      PMA_HOST: database:3306
      PMA_USER: wordpress
      PMA_PASSWORD: password
      VIRTUAL_HOST: 'pma.${PROJECT_HOST}'
      VIRTUAL_PORT: 80
    networks:
      - backend
      - frontend
