version: '3'

networks:
  backend:
  frontend:
    external:
      name: traefik

volumes:
  mysql:
  wordpress:

services:
  mysql:
    container_name: '${PROJECT_NAME}_mysql'
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - backend

  wordpress:
    container_name: '${PROJECT_NAME}_wordpress'
    image: wordpress:latest
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - wordpress:/var/www/html
      - ${PROJECT_ROOT}/wordpress:/var/www/html/wp-content
      - ../bin/wp-auto-login.php:/var/www/html/wp-auto-login.php
      - ../bin/install-wp.sh:/usr/local/bin/install-wp.sh:ro
      - ../bin/eject-wp.sh:/usr/local/bin/eject-wp.sh:ro
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini:ro
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
    networks:
      - backend
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_HOST}`)"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"

  phpmyadmin:
    container_name: '${PROJECT_NAME}_phpmyadmin'
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini:ro
    environment:
      PMA_HOST: mysql:3306
      PMA_USER: wordpress
      PMA_PASSWORD: password
    networks:
      - backend
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma${PROJECT_NAME}.rule=Host(`pma.${PROJECT_HOST}`)"
      - "traefik.http.services.pma${PROJECT_NAME}.loadbalancer.server.port=80"
