version: '3'

networks:
  backend:
  frontend:
    external:
      name: nginx_proxy

services:
  database:
    image: mysql:5.7
    volumes:
      - ${PROJECT_ROOT}/_database:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - backend

  wordpress:
    image: wordpress:latest
    depends_on:
      - database
    expose:
      - '80'
    volumes:
      - ${PROJECT_ROOT}/wordpress:/var/www/html
      - ../bin/install-wp.sh:/usr/local/bin/install-wp.sh
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
      VIRTUAL_HOST: '${VIRTUAL_HOST}'
      VIRTUAL_PORT: 80
    networks:
      - backend
      - frontend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    expose:
      - '80'
    restart: unless-stopped
    environment:
      PMA_HOST: database:3306
      PMA_USER: wordpress
      PMA_PASSWORD: password
      VIRTUAL_HOST: 'pma.${VIRTUAL_HOST}'
      VIRTUAL_PORT: 80
    networks:
      - backend
      - frontend
