version: '3.5'

networks:
  ejected_backend:
  ejected_frontend:
    driver: bridge

services:
  mysql:
    container_name: '${PROJECT_NAME}_ejected_mysql'
    image: mariadb
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - ${PROJECT_ROOT}/_database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - ejected_backend

  wordpress:
    container_name: '${PROJECT_NAME}_ejected_wordpress'
    image: wordpress:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - '8080:80'
    volumes:
      - ejected_wordpress_data:/var/www/html
      - ${PROJECT_ROOT}/wordpress:/var/www/html/wp-content
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini:ro
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
    networks:
      - ejected_backend
      - ejected_frontend

  phpmyadmin:
    container_name: '${PROJECT_NAME}_ejected_phpmyadmin'
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql:3306
      PMA_USER: wordpress
      PMA_PASSWORD: password
    networks:
      - ejected_backend
      - ejected_frontend

volumes:
  ejected_wordpress_data:
