version: '3'

networks:
  backend:
  frontend:
    driver: bridge

volumes:
  mysql:
  wordpress:

services:
  mysql:
    container_name: '${PROJECT_NAME}_mysql'
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - backend

  wordpress:
    container_name: '${PROJECT_NAME}_wordpress'
    image: wordpress:latest
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - wordpress:/var/www/html
      - ${PROJECT_ROOT}/wordpress/plugins:/var/www/html/wp-content/plugins
      - ${PROJECT_ROOT}/wordpress/themes:/var/www/html/wp-content/themes
      - ${PROJECT_ROOT}/wordpress/debug.log:/var/www/html/wp-content/debug.log
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
    networks:
      - backend
      - frontend
    ports:
      - '8080:80'

  phpmyadmin:
    container_name: '${PROJECT_NAME}_phpmyadmin'
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini:ro
    environment:
      PMA_HOST: mysql:3306
      PMA_USER: wordpress
      PMA_PASSWORD: password
    networks:
      - backend
      - frontend
    ports:
      - '8081:80'
